In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
import numpy as np

In [4]:
x = np.array([2,4,7,8,9,42,2,35])

In [5]:
pd.Series(x)

0     2
1     4
2     7
3     8
4     9
5    42
6     2
7    35
dtype: int32

In [6]:
x = np.array([[1,2,3,4,5],
              [6,7,4,5,3],
              [11,18,21,23,15],
             [21,23,25,2,5]])

In [7]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  4  5  3]
 [11 18 21 23 15]
 [21 23 25  2  5]]


In [8]:
x[0][0]

1

In [10]:
x[0:3,0:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 18]])

In [11]:
names = ['Terminator','Robot','Avengers','Hulk','Thor','Spiderman','Batman',
        'Superman','Baahubali','Narnia','Dhamaal','Hera Pheri']
ratings = [5,5,4,4,5,4,4,5,5,3,4,4]
category = ['action','action','action','action','action','drama','drama',
           'action','drama','drama','comedy','comedy']
dataset = {
    "movie_name" : names,
    "ratings" : ratings,
    "category" : category
}

In [12]:
df = pd.DataFrame(dataset)

In [13]:
df

category  movie_name  ratings
0    action  Terminator        5
1    action       Robot        5
2    action    Avengers        4
3    action        Hulk        4
4    action        Thor        5
5     drama   Spiderman        4
6     drama      Batman        4
7    action    Superman        5
8     drama   Baahubali        5
9     drama      Narnia        3
10   comedy     Dhamaal        4
11   comedy  Hera Pheri        4

In [16]:
df[df['category'] == 'action']

category  movie_name  ratings
0   action  Terminator        5
1   action       Robot        5
2   action    Avengers        4
3   action        Hulk        4
4   action        Thor        5
7   action    Superman        5

In [18]:
df[df['ratings'] > 4]

category  movie_name  ratings
0   action  Terminator        5
1   action       Robot        5
4   action        Thor        5
7   action    Superman        5
8    drama   Baahubali        5

In [20]:
df[(df['ratings'] > 4) | (df['category'] == 'comedy')]

category  movie_name  ratings
0    action  Terminator        5
1    action       Robot        5
4    action        Thor        5
7    action    Superman        5
8     drama   Baahubali        5
10   comedy     Dhamaal        4
11   comedy  Hera Pheri        4